// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TransactionType string

const (
	TransactionTypeFund     TransactionType = "fund"
	TransactionTypeWithdraw TransactionType = "withdraw"
	TransactionTypeBuy      TransactionType = "buy"
	TransactionTypeSell     TransactionType = "sell"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType `json:"transaction_type"`
	Valid           bool            `json:"valid"` // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

// Active treasury holdings (bills, notes, bonds)
type Holding struct {
	ID              int32            `json:"id"`
	UserID          int32            `json:"user_id"`
	Term            string           `json:"term"`
	Amount          pgtype.Numeric   `json:"amount"`
	YieldAtPurchase pgtype.Numeric   `json:"yield_at_purchase"`
	PurchaseDate    pgtype.Timestamp `json:"purchase_date"`
	RemainingAmount pgtype.Numeric   `json:"remaining_amount"`
	// Amount received at maturity
	FaceValue pgtype.Numeric `json:"face_value"`
	// Actual price paid (discounted for T-Bills)
	PurchasePrice pgtype.Numeric `json:"purchase_price"`
	// Type of treasury security: bill, note, or bond
	SecurityType pgtype.Text `json:"security_type"`
}

// All financial transactions (deposits, withdrawals, treasury trades)
type Transaction struct {
	ID                 int32            `json:"id"`
	UserID             int32            `json:"user_id"`
	Timestamp          pgtype.Timestamp `json:"timestamp"`
	Type               TransactionType  `json:"type"`
	Term               pgtype.Text      `json:"term"`
	Amount             pgtype.Numeric   `json:"amount"`
	YieldAtTransaction pgtype.Numeric   `json:"yield_at_transaction"`
	BalanceAfter       pgtype.Numeric   `json:"balance_after"`
	// References the holding for buy/sell transactions
	HoldingID pgtype.Int4 `json:"holding_id"`
}

// Daily treasury yield curve data from treasury.gov, partitioned by year
type TreasuryYield struct {
	Date     pgtype.Date    `json:"date"`
	Bc1month pgtype.Numeric `json:"bc_1month"`
	Bc3month pgtype.Numeric `json:"bc_3month"`
	Bc6month pgtype.Numeric `json:"bc_6month"`
	Bc1year  pgtype.Numeric `json:"bc_1year"`
	Bc2year  pgtype.Numeric `json:"bc_2year"`
	Bc5year  pgtype.Numeric `json:"bc_5year"`
	Bc10year pgtype.Numeric `json:"bc_10year"`
	Bc30year pgtype.Numeric `json:"bc_30year"`
}

// User accounts with current balance
type User struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Balance   pgtype.Numeric     `json:"balance"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
