// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateHolding(ctx context.Context, arg CreateHoldingParams) (Holding, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteNonMonthlySamples(ctx context.Context, date pgtype.Date) error
	DeleteNonWeeklySamples(ctx context.Context, date pgtype.Date) error
	DeleteUser(ctx context.Context, id int32) error
	GetActiveHoldingsByUser(ctx context.Context, userID int32) ([]Holding, error)
	GetDistinctYieldYears(ctx context.Context) ([]int32, error)
	GetHoldingByID(ctx context.Context, id int32) (Holding, error)
	GetHoldingsByUser(ctx context.Context, userID int32) ([]Holding, error)
	GetLatestYield(ctx context.Context) (TreasuryYield, error)
	GetTransactionByID(ctx context.Context, id int32) (Transaction, error)
	GetTransactionsByUser(ctx context.Context, userID int32) ([]Transaction, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserForUpdate(ctx context.Context, id int32) (User, error)
	GetYieldsByDateRange(ctx context.Context, arg GetYieldsByDateRangeParams) ([]TreasuryYield, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateHoldingRemainingAmount(ctx context.Context, arg UpdateHoldingRemainingAmountParams) (Holding, error)
	UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) (User, error)
	UpsertTreasuryYield(ctx context.Context, arg UpsertTreasuryYieldParams) error
}

var _ Querier = (*Queries)(nil)
