// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id,
    type,
    term,
    amount,
    yield_at_transaction,
    balance_after,
    holding_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, timestamp, type, term, amount, yield_at_transaction, balance_after, holding_id
`

type CreateTransactionParams struct {
	UserID             int32           `json:"user_id"`
	Type               TransactionType `json:"type"`
	Term               pgtype.Text     `json:"term"`
	Amount             pgtype.Numeric  `json:"amount"`
	YieldAtTransaction pgtype.Numeric  `json:"yield_at_transaction"`
	BalanceAfter       pgtype.Numeric  `json:"balance_after"`
	HoldingID          pgtype.Int4     `json:"holding_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Type,
		arg.Term,
		arg.Amount,
		arg.YieldAtTransaction,
		arg.BalanceAfter,
		arg.HoldingID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Timestamp,
		&i.Type,
		&i.Term,
		&i.Amount,
		&i.YieldAtTransaction,
		&i.BalanceAfter,
		&i.HoldingID,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, user_id, timestamp, type, term, amount, yield_at_transaction, balance_after, holding_id FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id int32) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Timestamp,
		&i.Type,
		&i.Term,
		&i.Amount,
		&i.YieldAtTransaction,
		&i.BalanceAfter,
		&i.HoldingID,
	)
	return i, err
}

const getTransactionsByUser = `-- name: GetTransactionsByUser :many
SELECT id, user_id, timestamp, type, term, amount, yield_at_transaction, balance_after, holding_id FROM transactions
WHERE user_id = $1
ORDER BY timestamp DESC
`

func (q *Queries) GetTransactionsByUser(ctx context.Context, userID int32) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Timestamp,
			&i.Type,
			&i.Term,
			&i.Amount,
			&i.YieldAtTransaction,
			&i.BalanceAfter,
			&i.HoldingID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
