// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: yields.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestYield = `-- name: GetLatestYield :one
SELECT date, bc_1month, bc_3month, bc_6month, bc_1year, bc_2year, bc_5year, bc_10year, bc_30year FROM treasury_yields
ORDER BY date DESC
LIMIT 1
`

func (q *Queries) GetLatestYield(ctx context.Context) (TreasuryYield, error) {
	row := q.db.QueryRow(ctx, getLatestYield)
	var i TreasuryYield
	err := row.Scan(
		&i.Date,
		&i.Bc1month,
		&i.Bc3month,
		&i.Bc6month,
		&i.Bc1year,
		&i.Bc2year,
		&i.Bc5year,
		&i.Bc10year,
		&i.Bc30year,
	)
	return i, err
}

const getMaxYieldDate = `-- name: GetMaxYieldDate :one
SELECT COALESCE(MAX(date), '1900-01-01'::date) AS max_date
FROM treasury_yields
`

func (q *Queries) GetMaxYieldDate(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, getMaxYieldDate)
	var max_date interface{}
	err := row.Scan(&max_date)
	return max_date, err
}

const getYieldsByDateRange = `-- name: GetYieldsByDateRange :many
SELECT date, bc_1month, bc_3month, bc_6month, bc_1year, bc_2year, bc_5year, bc_10year, bc_30year FROM treasury_yields
WHERE date >= $1 AND date <= $2
ORDER BY date ASC
`

type GetYieldsByDateRangeParams struct {
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

func (q *Queries) GetYieldsByDateRange(ctx context.Context, arg GetYieldsByDateRangeParams) ([]TreasuryYield, error) {
	rows, err := q.db.Query(ctx, getYieldsByDateRange, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TreasuryYield{}
	for rows.Next() {
		var i TreasuryYield
		if err := rows.Scan(
			&i.Date,
			&i.Bc1month,
			&i.Bc3month,
			&i.Bc6month,
			&i.Bc1year,
			&i.Bc2year,
			&i.Bc5year,
			&i.Bc10year,
			&i.Bc30year,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTreasuryYield = `-- name: UpsertTreasuryYield :exec
INSERT INTO treasury_yields (
    date, bc_1month, bc_3month, bc_6month, bc_1year,
    bc_2year, bc_5year, bc_10year, bc_30year
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) ON CONFLICT (date) DO NOTHING
`

type UpsertTreasuryYieldParams struct {
	Date     pgtype.Date    `json:"date"`
	Bc1month pgtype.Numeric `json:"bc_1month"`
	Bc3month pgtype.Numeric `json:"bc_3month"`
	Bc6month pgtype.Numeric `json:"bc_6month"`
	Bc1year  pgtype.Numeric `json:"bc_1year"`
	Bc2year  pgtype.Numeric `json:"bc_2year"`
	Bc5year  pgtype.Numeric `json:"bc_5year"`
	Bc10year pgtype.Numeric `json:"bc_10year"`
	Bc30year pgtype.Numeric `json:"bc_30year"`
}

func (q *Queries) UpsertTreasuryYield(ctx context.Context, arg UpsertTreasuryYieldParams) error {
	_, err := q.db.Exec(ctx, upsertTreasuryYield,
		arg.Date,
		arg.Bc1month,
		arg.Bc3month,
		arg.Bc6month,
		arg.Bc1year,
		arg.Bc2year,
		arg.Bc5year,
		arg.Bc10year,
		arg.Bc30year,
	)
	return err
}
